spring:
  application:
    name: blog-web-service
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/iblog?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      max-idle: 10
      max-wait-millis: 30
      min-idle: 5
      initial-size: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
server:
  port: 8080
  undertow:
    io-threads: 4
    worker-threads: 20
    buffer-size: 1024
    direct-buffers: true
logging:
  level:
    root: warn
    org:
      springframework:
        web: debug